language: java
jdk:
  - oraclejdk8
  - openjdk7
  
before_script:
  - cd qwirkle
  
 after_success:
  - util/deploy_snapshot.sh
  - util/update_snapshot_docs.sh

env:
  global:
  - secure: "aBaPGk97lpUv4y8Y82fckDMsvEAJMzyEKWHn0uwDZedXXPN09QAZo9tLDi3xUp1IgdPTc2lsM45ww7IAm5nMd0KU+eTjfgDd3LjUAUzG/aIX0Cgpu/yUm0JAUFgKP1lEr34Mv27BBleaJ+xShtgHWoCjsQTPexVSPbZYPSKIjEYkV8tim4rqXbVbI+9es3tWoQ0zCGYST0oOVN1Ictg5wTmxaNCE4D70ZV
qsX7Kf/tIF8DIaWYhiga2NxylfOhH1uXHz/lEZsEw0mIVgopJQhlZNrqFxxGkltGBxdfCq9G7GxC/0uM95rctBib30as+pyOCFg1Qfy+zyQrvR8pK7VJQKMazDeAd8mqzg67JZ6xrJIRrDAHPe5ljUWe4dj4tIxWDlDLWPYhXpOd4gs29emXFQSxMMwik1Z+4Z7leBVkSqTqWoDVZhRM4yyma74R0KVRyLnu1WVFhgF
4/Q7kBxUzkPU+HHwQTqgif1NjoXUvdbOj+s5HUhIbLpezSMG6tU+iX36XSkdyuEUFOCp3LmA8HQv8BTDvXMbOmnIZmixdth8TqZDlwsPxwXuhEmL8MlPglZk29FNvCK2qFvUZ9plpqRxVaWFaEmhFUUtxpgeRw7vC2/7uPWowZzl8i3wIMR8zeg5t8yjzKEWNyhH/R1FQtUFHKAmLDk4LLYjW4="
